### ISSUE TITLE
[SOLID] Rector\SOLID\Rector\Class_\FinalizeClassesWithoutChildrenRector: should not change Doctrine Entities

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector#1639]
When using the level `solid`, it will turn every non-final class to final, including Doctrine entities.
But as stated in Doctrine's documentation : 

> An entity is a lightweight, persistent domain object. An entity can be any regular PHP class observing the following restrictions: - An entity class must not be final or contain final methods.

So it would be nice if there was a way for Rector to detect `@ORM\Entity` annotation and not process these classes.

**Comment by gnutix** [comment]
Sorry, mistake from my side... It's handled correctly already.

**Comment by gnutix** [comment]
I'm encountering this issue again : 

```
docker run --rm -v $(pwd):/app rector_phar process --ansi --autoload-file /app/vendor/autoload.php --config /app/rector.yaml /app/src /app/tests --dry-run
Rector 0.6.x-dev@9a330e2
Config file: app/rector.yaml

 1062/1062 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

1 file with changes
===================

1) app/src/SomeNamespace/ExpenseTag.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -12,7 +12,7 @@
  * @ORM\Table(name="expense_tag")
  * @ORM\Entity()
  */
-class ExpenseTag
+final class ExpenseTag
 {
     /**
      * @var Expense
    ----------- end diff -----------

Applied rules:

 * Rector\SOLID\Rector\Class_\FinalizeClassesWithoutChildrenRector
```

Here's the file : 

```php 
<?php

declare(strict_types=1);

namespace App\SomeNamespace;

use Doctrine\ORM\Mapping as ORM;
use SomeVendor\Snowflake\Snowflake;

/**
 * @ORM\HasLifecycleCallbacks
 * @ORM\Table(name="expense_tag")
 * @ORM\Entity()
 */
class ExpenseTag
{
    /**
     * @var Expense
     *
     * @ORM\Id
     * @ORM\ManyToOne(targetEntity="Expense", inversedBy="expenseTags")
     */
    private $expense;

    /**
     * @var Snowflake
     *
     * @ORM\Id
     * @ORM\Column(name="tag_id", type="snowflake")
     */
    private $tagId;

    public function __construct(Expense $expense, Snowflake $tagId)
    {
        $this->expense = $expense;
        $this->tagId = $tagId;
    }

    public function tagId(): Snowflake
    {
        return $this->tagId;
    }
}
```

I've tried adding it "as is" in `packages/SOLID/tests/Rector/Class_/FinalizeClassesWithoutChildrenRector/Fixture` and run the tests with `phpunit packages/SOLID/tests/Rector/Class_/FinalizeClassesWithoutChildrenRector/FinalizeClassesWithoutChildrenRectorTest.php`, and it passed... so I don't really understand why Rector tries to change it in my code base. Any thoughts ?

**Comment by TomasVotruba** [comment]
> Could it be because it's running within Docker or with the phar ? (and Doctrine's annotation is not properly recognized ?)

It probably is.

It would be great if you'd add this test case to https://github.com/rectorphp/rector-prefixed `e2e` test. I think it will be related to prefixed version

**Comment by gnutix** [comment]
I fixed it by running Rector from the root of the project (instead of the root of the Docker container), see [the 2nd point of my comment here](https://github.com/rectorphp/rector/issues/2417#issuecomment-569798003)

**Comment by TomasVotruba** [comment]
Could you update README for Docker to prevent that?

**Comment by gnutix** [comment]
Not sure it applies to the `rector/rector` container. I'm not using it, as I needed to be able to freeze to a specific commit of Rector - so I'm using the PhpStan container in which I require rector, like this : 

```
# Dockerfile
FROM phpstan/phpstan:0.12
RUN apk --update --progress --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.9/community add \
    php7-dom \
    php7-xmlwriter \
    && composer global require \
        rector/rector:"dev-master#2c3724b" #rector from December 30th 2019
WORKDIR /app
ENTRYPOINT ["rector"]
```

**Comment by TomasVotruba** [comment]
Ok :+1:

**Comment by gnutix** [comment]
False hope... the issue is not resolved. Now that I managed to run Rector without issues with our custom phpstan.neon (by renaming it), I can get rid of Docker and run rector.phar directly (which is much more robust / fast - at least on my machine). But the issue is back.

I managed to simplify it that much : 

```
$ php rector.phar process --rule "Rector\SOLID\Rector\Class_\FinalizeClassesWithoutChildrenRector" --dry-run src/SomeNamespace/ExpenseTag.php 
Rector 0.6.x-dev@f4bfaeb
Config file: rector.yaml

 3/3 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

1 file with changes
===================

1) src/Domain/Expenses/ExpenseTag.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -12,7 +12,7 @@
  * @ORM\Table(name="expense_tag")
  * @ORM\Entity()
  */
-class ExpenseTag
+final class ExpenseTag
 {
     /**
      * @var Expense
    ----------- end diff -----------

Applied rules:

 * Rector\SOLID\Rector\Class_\FinalizeClassesWithoutChildrenRector
```

I've tried to set the same thing in the playground repo, but it passed there :

```
Rector dev-master@d83ea25
Config file: rector.yaml

[parsing] src/Domain/Expenses/ExpenseTag.php
[refactoring] src/Domain/Expenses/ExpenseTag.php
[printing] src/Domain/Expenses/ExpenseTag.php

 [OK] Rector is done! 0 changed files                                                             
```

**Comment by TomasVotruba** [comment]
I'd debug `FinalizeClassesWithoutChildrenRector`

This method should return true: https://github.com/rectorphp/rector/blob/d83ea25cb5e1bdc04a5d2ece46c61824eda35a89/packages/SOLID/src/Rector/Class_/FinalizeClassesWithoutChildrenRector.php#L81

**Comment by gnutix** [comment]
@TomasVotruba I took some time to investigate. Adding `dd($phpDocNode);` after line [`$phpDocNode = $this->phpDocParser->parse($tokenIterator);`](https://github.com/rectorphp/rector/blob/master/packages/BetterPhpDocParser/src/PhpDocInfo/PhpDocInfoFactory.php#L75) gives : 

### `bin/rector`

```
  -phpDocNode: Rector\BetterPhpDocParser\Attributes\Ast\PhpDoc\AttributeAwarePhpDocNode^ {#6325
    +children: array:1 [
      0 => Rector\BetterPhpDocParser\Attributes\Ast\PhpDoc\AttributeAwarePhpDocTagNode^ {#6324
        +name: "@ORM\Entity"
        +value: Rector\BetterPhpDocParser\PhpDocNode\Doctrine\Class_\EntityTagValueNode^ {#6315
          -repositoryClass: null
          -readOnly: false
          #orderedVisibleItems: []
          #hasNewlineBeforeClosing: false
          #hasNewlineAfterOpening: false
          -attributes: []
        }
```

### `tmp/rector.phar`

```
  -phpDocNode: Rector\BetterPhpDocParser\Attributes\Ast\PhpDoc\AttributeAwarePhpDocNode^ {#7834
    +children: array:1 [
      0 => Rector\BetterPhpDocParser\Attributes\Ast\PhpDoc\AttributeAwarePhpDocTagNode^ {#7833
        +name: "@ORM"
        +value: Rector\BetterPhpDocParser\Attributes\Ast\PhpDoc\AttributeAwareGenericTagValueNode^ {#7832
          +value: "\Entity"
          -attributes: []
        }
```

So `\PHPStan\PhpDocParser\Parser\PhpDocParser::parse()` returns a different result, which then breaks your code.

What should I do ? Open a new issue on PHPStan's repo ? Invite ondrejmirtes to discuss it here ?

**Comment by TomasVotruba** [comment]
I have a theory... It might related to remvoed stubs, where are annotations located.

Without those, Rector doesn't know about these classes.

**Comment by gnutix** [comment]
I don't think it could, as I reopened this issue 11 days ago and you merged the [removal of the `stubs/` folder from rector.phar](https://github.com/rectorphp/rector/pull/2609) two days ago.

**Comment by gnutix** [comment]
We now know that the same issue happens with ECS and `PhpCsFixer\Fixer\ClassNotation\FinalClassFixer`.

**Comment by TomasVotruba** [comment]
Any update on this? Just fixed partially-reated embeddables here: https://github.com/rectorphp/rector/pull/2921

If still on, we'll need failing Github Action to confirm.

**Comment by TomasVotruba** [comment]
Demo link is needed: https://getrector.org/demo

**Comment by gnutix** [comment]
I've tried running the current master version, and still get these : 

```
10) src/Domain/Expenses/ExpenseTag.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -12,7 +12,7 @@
  * @ORM\Table()
  * @ORM\Entity
  */
-class ExpenseTag
+final class ExpenseTag
 {
     /**
      * @var Expense
    ----------- end diff -----------

Applied rules:

 * Rector\SOLID\Rector\Class_\FinalizeClassesWithoutChildrenRector
```

https://getrector.org/demo/ebc84c7a-c901-46bf-9857-14b226cedd75

**Comment by TomasVotruba** [comment]
When you remove the HasLifecycle annotatoin (fixed in `master`), the CI works correctly: https://getrector.org/demo/bf923428-7655-4f3b-8678-1aa5155fbd05#result

**Comment by gnutix** [comment]
I upgraded to v0.7.2 and this issue still persists using rector.phar. I won't reopen, as I can't produce a demo.
