### ISSUE TITLE
Break after a fresh install (create-project)

### ISSUE THREAD

**Issue by Soullivaneuh** [rectorphp/rector#178]
After a fresh install trough create-project, I did:

```
$ ~/tmp/rector/bin/rector process --level symfony33 src
```

And I got:

```
PHP Warning:  array_intersect(): Argument #1 is not an array in /home/sullivan/tmp/rector/src/NodeAnalyzer/MethodCallAnalyzer.php on line 133
PHP Stack trace:
PHP   1. {main}() /home/sullivan/tmp/rector/bin/rector:0
PHP   2. require_once() /home/sullivan/tmp/rector/bin/rector:4
PHP   3. Rector\Console\Application->run() /home/sullivan/tmp/rector/bin/rector.php:37
PHP   4. Rector\Console\Application->doRun() /home/sullivan/tmp/rector/vendor/symfony/console/Application.php:122
PHP   5. Rector\Console\Application->doRunCommand() /home/sullivan/tmp/rector/vendor/symfony/console/Application.php:216
PHP   6. Rector\Console\Command\ProcessCommand->run() /home/sullivan/tmp/rector/vendor/symfony/console/Application.php:858
PHP   7. Rector\Console\Command\ProcessCommand->execute() /home/sullivan/tmp/rector/vendor/symfony/console/Command/Command.php:240
PHP   8. Rector\Console\Command\ProcessCommand->processFiles() /home/sullivan/tmp/rector/src/Console/Command/ProcessCommand.php:86
PHP   9. Rector\Application\FileProcessor->processFile() /home/sullivan/tmp/rector/src/Console/Command/ProcessCommand.php:116
PHP  10. Rector\NodeTraverserQueue\NodeTraverserQueue->processFileInfo() /home/sullivan/tmp/rector/src/Application/FileProcessor.php:49
PHP  11. Rector\NodeTraverser\RectorNodeTraverser->traverse() /home/sullivan/tmp/rector/packages/NodeTraverserQueue/src/NodeTraverserQueue.php:86
PHP  12. Rector\NodeTraverser\RectorNodeTraverser->traverseArray() /home/sullivan/tmp/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:85
PHP  13. Rector\NodeTraverser\RectorNodeTraverser->traverseNode() /home/sullivan/tmp/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:197
PHP  14. Rector\NodeTraverser\RectorNodeTraverser->traverseArray() /home/sullivan/tmp/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:108
PHP  15. Rector\NodeTraverser\RectorNodeTraverser->traverseNode() /home/sullivan/tmp/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:197
PHP  16. Rector\NodeTraverser\RectorNodeTraverser->traverseArray() /home/sullivan/tmp/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:108
PHP  17. Rector\NodeTraverser\RectorNodeTraverser->traverseNode() /home/sullivan/tmp/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:197
PHP  18. Rector\NodeTraverser\RectorNodeTraverser->traverseArray() /home/sullivan/tmp/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:108
PHP  19. Rector\NodeTraverser\RectorNodeTraverser->traverseNode() /home/sullivan/tmp/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:197
PHP  20. Rector\Rector\Dynamic\MethodNameReplacerRector->enterNode() /home/sullivan/tmp/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:115
PHP  21. Rector\Rector\Dynamic\MethodNameReplacerRector->isCandidate() /home/sullivan/tmp/rector/src/Rector/AbstractRector.php:58
PHP  22. Rector\NodeAnalyzer\MethodCallAnalyzer->matchTypes() /home/sullivan/tmp/rector/src/Rector/Dynamic/MethodNameReplacerRector.php:77
PHP  23. array_intersect() /home/sullivan/tmp/rector/src/NodeAnalyzer/MethodCallAnalyzer.php:133

                                                                                                                        
 [ERROR] Call to undefined method PhpParser\Node\Expr\Variable::toString() in                                           
         /home/sullivan/tmp/rector/packages/NodeTypeResolver/src/PerNodeTypeResolver/PropertyFetchTypeResolver.php on   
         line 53                                                                                                                                                                                                 
```

Note that the `array_intersect` warning appears multiple time before failing.

**Comment by TomasVotruba** [comment]
Have you used `dev` version?

**Comment by Soullivaneuh** [comment]
Maybe not, I just follow this command: https://github.com/rectorphp/rector/blob/master/docs/HowUseWithOldPhp.md

Will try.

**Comment by TomasVotruba** [comment]
Ok, I'll look on it tomorrow

**Comment by TomasVotruba** [comment]
I'm finally here, thanks for patience.

Could you try latest version with this install?

```php
composer create-project rector/rector:@dev path-to-rector
```

If still fails, could you please provide content of `/home/sullivan/projects/nexylan/n-admin/src/AppBundle/Admin/AccountingAdmin.php`? Or at least minimal failing code, so I can simulate it.

On first sight, it looks like on a bug in php-parser itself, since it's refers 2 its classes.

**Comment by TomasVotruba** [comment]
First issue was resolved by:
https://github.com/rectorphp/rector/blob/a5cad527f808c4aaea67ecbc7910b96d123f4fdc/src/NodeAnalyzer/MethodCallAnalyzer.php#L39

I'm not able to reproduce the other one with code causing it. Moreover when the issue is possibly related to 3rd party package.

Feel free to try current `master` and reply here, if the issue still remains.

**Comment by Soullivaneuh** [comment]
Hey @TomasVotruba,

I just did a `composer create-project` as you told and tried again. Sadly, the error still occurs:

```
$ ~/tmp/rector/bin/rector process --level symfony33 src

4 Loaded Rectors
================

 - Rector\Rector\Contrib\Symfony\Console\ConsoleExceptionToErrorEventConstantRector
 - Rector\Rector\Dynamic\ArgumentReplacerRector
 - Rector\Rector\Dynamic\ClassReplacerRector
 - Rector\Rector\Dynamic\MethodNameReplacerRector

Processing files
================

   0/602 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0% < 1 secPHP Fatal error:  Declaration of PhpParser\Node\Scalar\LNumber::getSubNodeNames() must be compatible with PhpParser\Node::getSubNodeNames(): array in /home/sullivan/projects/nexylan/n-admin/vendor/nikic/php-parser/lib/PhpParser/Node/Scalar/LNumber.php on line 67
PHP Stack trace:
PHP   1. {main}() /home/sullivan/tmp/rector/bin/rector:0
PHP   2. require_once() /home/sullivan/tmp/rector/bin/rector:4
PHP   3. Rector\Console\Application->run() /home/sullivan/tmp/rector/bin/rector.php:43
PHP   4. Rector\Console\Application->doRun() /home/sullivan/tmp/rector/vendor/symfony/console/Application.php:143
PHP   5. Rector\Console\Application->doRunCommand() /home/sullivan/tmp/rector/vendor/symfony/console/Application.php:233
PHP   6. Rector\Console\Command\ProcessCommand->run() /home/sullivan/tmp/rector/vendor/symfony/console/Application.php:855
PHP   7. Rector\Console\Command\ProcessCommand->execute() /home/sullivan/tmp/rector/vendor/symfony/console/Command/Command.php:252
PHP   8. Rector\Console\Command\ProcessCommand->processFiles() /home/sullivan/tmp/rector/src/Console/Command/ProcessCommand.php:120
PHP   9. Rector\Console\Command\ProcessCommand->processFile() /home/sullivan/tmp/rector/src/Console/Command/ProcessCommand.php:149
PHP  10. Rector\Application\FileProcessor->processFile() /home/sullivan/tmp/rector/src/Console/Command/ProcessCommand.php:177
PHP  11. Rector\NodeTraverserQueue\NodeTraverserQueue->processFileInfo() /home/sullivan/tmp/rector/src/Application/FileProcessor.php:49
PHP  12. Rector\NodeTraverser\StandaloneTraverseNodeTraverser->traverse() /home/sullivan/tmp/rector/packages/NodeTraverserQueue/src/NodeTraverserQueue.php:74
PHP  13. PhpParser\NodeTraverser->traverse() /home/sullivan/tmp/rector/src/NodeTraverser/StandaloneTraverseNodeTraverser.php:49
PHP  14. PhpParser\NodeTraverser->traverseArray() /home/sullivan/tmp/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:85
PHP  15. PhpParser\NodeTraverser->traverseNode() /home/sullivan/tmp/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:197
PHP  16. PhpParser\NodeTraverser->traverseArray() /home/sullivan/tmp/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:108
PHP  17. Rector\NodeTypeResolver\NodeVisitor\TypeNodeVisitor->enterNode() /home/sullivan/tmp/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:179
PHP  18. Rector\NodeTypeResolver\NodeTypeResolver->resolve() /home/sullivan/tmp/rector/packages/NodeTypeResolver/src/NodeVisitor/TypeNodeVisitor.php:52
PHP  19. Rector\NodeTypeResolver\PerNodeTypeResolver\ClassLikeTypeResolver->resolve() /home/sullivan/tmp/rector/packages/NodeTypeResolver/src/NodeTypeResolver.php:36
PHP  20. Rector\NodeAnalyzer\ClassLikeAnalyzer->resolveTypeAndParentTypes() /home/sullivan/tmp/rector/packages/NodeTypeResolver/src/PerNodeTypeResolver/ClassLikeTypeResolver.php:33
PHP  21. Rector\NodeAnalyzer\ClassLikeAnalyzer->resolveExtendsTypes() /home/sullivan/tmp/rector/src/NodeAnalyzer/ClassLikeAnalyzer.php:51
PHP  22. Rector\BetterReflection\Reflector\SmartClassReflector->getClassParents() /home/sullivan/tmp/rector/src/NodeAnalyzer/ClassLikeAnalyzer.php:101
PHP  23. Rector\BetterReflection\Reflection\ReflectionClass->getParentClassNames() /home/sullivan/tmp/rector/packages/BetterReflection/src/Reflector/SmartClassReflector.php:82
PHP  24. Rector\BetterReflection\Reflection\ReflectionClass->getInheritanceClassHierarchy() /home/sullivan/tmp/rector/vendor/rector/better-reflection/src/Reflection/ReflectionClass.php:825
PHP  25. Rector\BetterReflection\Reflection\ReflectionClass->getParentClass() /home/sullivan/tmp/rector/vendor/rector/better-reflection/src/Reflection/ReflectionClass.php:1216
PHP  26. Rector\BetterReflection\Reflector\ClassReflector->reflect() /home/sullivan/tmp/rector/vendor/rector/better-reflection/src/Reflection/ReflectionClass.php:807
PHP  27. Rector\BetterReflection\SourceLocator\Type\MemoizingSourceLocator->locateIdentifier() /home/sullivan/tmp/rector/vendor/rector/better-reflection/src/Reflector/ClassReflector.php:37
PHP  28. Rector\BetterReflection\SourceLocator\Type\AggregateSourceLocator->locateIdentifier() /home/sullivan/tmp/rector/vendor/rector/better-reflection/src/SourceLocator/Type/MemoizingSourceLocator.php:42
PHP  29. Rector\BetterReflection\SourceLocator\Type\AutoloadSourceLocator->locateIdentifier() /home/sullivan/tmp/rector/vendor/rector/better-reflection/src/SourceLocator/Type/AggregateSourceLocator.php:37
PHP  30. Rector\BetterReflection\SourceLocator\Ast\Locator->findReflection() /home/sullivan/tmp/rector/vendor/rector/better-reflection/src/SourceLocator/Type/AbstractSourceLocator.php:50
PHP  31. Rector\BetterReflection\SourceLocator\Ast\Locator->findReflectionsOfType() /home/sullivan/tmp/rector/vendor/rector/better-reflection/src/SourceLocator/Ast/Locator.php:55
PHP  32. PhpParser\Parser\Multiple->parse() /home/sullivan/tmp/rector/vendor/rector/better-reflection/src/SourceLocator/Ast/Locator.php:78
PHP  33. PhpParser\Parser\Multiple->tryParse() /home/sullivan/tmp/rector/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php:31
PHP  34. PhpParser\Parser\Php7->parse() /home/sullivan/tmp/rector/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php:50
PHP  35. PhpParser\Parser\Php7->doParse() /home/sullivan/tmp/rector/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:159
PHP  36. PhpParser\Parser\Php7->PhpParser\Parser\{closure}() /home/sullivan/tmp/rector/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:285
PHP  37. PhpParser\Parser\Php7->parseLNumber() /home/sullivan/tmp/rector/vendor/nikic/php-parser/lib/PhpParser/Parser/Php7.php:2131
PHP  38. spl_autoload_call() /home/sullivan/tmp/rector/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:687
PHP  39. Composer\Autoload\ClassLoader->loadClass() /home/sullivan/tmp/rector/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:687
PHP  40. Composer\Autoload\includeFile() /home/sullivan/tmp/rector/vendor/composer/ClassLoader.php:322
```

Tell me if you need more info.

**Comment by TomasVotruba** [comment]
How exactly did you install the project?
Also I need a file in your `/src`, that is causing this.

After that, I can copy-paste your process to my shell and debug myself.

**Comment by Soullivaneuh** [comment]
@TomasVotruba Sorry for the late reply. I indeed did a fresh install again (dev-master), and it seems to work now. Thanks!

**Comment by TomasVotruba** [comment]
@Soullivaneuh Thanks for reaching out. Lot of work was done by @carusogabriel , who fixed a lot in this matter
