### ISSUE TITLE
[ERROR] Could not process "<file>" file, due to: "".

### ISSUE THREAD

**Issue by UFTimmy** [rectorphp/rector#2732]
| Subject        | Details                                                               |
| :------------- | :-------------------------------------------------------------------- |
| Rector version | dev-master@d0a2b47 (checked out a few minutes ago)                  |
| PHP version    | 7.2.12                                       |
| Full Command   | .\vendor\bin\rector.bat process .\src\ --dry-run --set=type-declaration --only=Rector\TypeDeclaration\Rector\FunctionLike\ReturnTypeDeclarationRector --debug           | 
| Demo link      |   | 
| rector.yaml    | No rector.yaml              | 

## Current Behaviour 

This is probably related to #2614 that I opened before. The fix there made that exception go away, but it introduced a new one, this time with an empty message.

Here's the debug output:

```
File "C:\path\to\project\rector-test/vendor/autoload.php" is about to be loaded in "AutoloadIncluder::includeCwdVendorAutoloadIfExists()" on line 65"
File "C:\path\to\project\rector-test\vendor\rector\rector/../../autoload.php" is about to be loaded in "AutoloadIncluder::autoloadProjectAutoloaderFile()" on line 97"
Rector dev-master@d0a2b47

[parsing] src/Lesson.php
[parsing] src/Topic.php
[refactoring] src/Lesson.php
[refactoring] src/Topic.php
    [applying] Rector\TypeDeclaration\Rector\FunctionLike\ReturnTypeDeclarationRector
PHP Fatal error:  Uncaught Rector\Exception\NotImplementedException in C:\path\to\project\rector-test\vendor\rector\rector\packages\PHPStanStaticTypeMapper\src\TypeMapper\IntersectionTypeMapper.php:57
Stack trace:
#0 C:\path\to\project\rector-test\vendor\rector\rector\packages\PHPStanStaticTypeMapper\src\PHPStanStaticTypeMapper.php(55): Rector\PHPStanStaticTypeMapper\TypeMapper\IntersectionTypeMapper->mapToPhpParserNode(Object(PHPStan\Type\IntersectionType), NULL)
#1 C:\path\to\project\rector-test\vendor\rector\rector\packages\NodeTypeResolver\src\StaticTypeMapper.php(116): Rector\PHPStanStaticTypeMapper\PHPStanStaticTypeMapper->mapToPhpParserNode(Object(PHPStan\Type\IntersectionType), NULL)
#2 C:\path\to\project\rector-test\vendor\rector\rector\packages\TypeDeclaration\src\Rector\FunctionLike\ReturnTypeDeclarationRector.php(200): Rector\NodeTypeResolver\StaticTypeMapper->mapPHPStanTypeToPhpParserNode(Object(PHPStan\Type\Interse in C:\path\to\project\rector-test\vendor\rector\rector\packages\PHPStanStaticTypeMapper\src\TypeMapper\IntersectionTypeMapper.php on line 57
Fatal error: Uncaught Rector\Exception\NotImplementedException in C:\path\to\project\rector-test\vendor\rector\rector\packages\PHPStanStaticTypeMapper\src\TypeMapper\IntersectionTypeMapper.php:57
Stack trace:
#0 C:\path\to\project\rector-test\vendor\rector\rector\packages\PHPStanStaticTypeMapper\src\PHPStanStaticTypeMapper.php(55): Rector\PHPStanStaticTypeMapper\TypeMapper\IntersectionTypeMapper->mapToPhpParserNode(Object(PHPStan\Type\IntersectionType), NULL)
#1 C:\path\to\project\rector-test\vendor\rector\rector\packages\NodeTypeResolver\src\StaticTypeMapper.php(116): Rector\PHPStanStaticTypeMapper\PHPStanStaticTypeMapper->mapToPhpParserNode(Object(PHPStan\Type\IntersectionType), NULL)
#2 C:\path\to\project\rector-test\vendor\rector\rector\packages\TypeDeclaration\src\Rector\FunctionLike\ReturnTypeDeclarationRector.php(200): Rector\NodeTypeResolver\StaticTypeMapper->mapPHPStanTypeToPhpParserNode(Object(PHPStan\Type\Interse in C:\path\to\project\rector-test\vendor\rector\rector\packages\PHPStanStaticTypeMapper\src\TypeMapper\IntersectionTypeMapper.php on line 57
```

## Minimal PHP Code Causing Issue

I created a super simple Github repo that reproduces the issue, the same one as #2614 

https://github.com/UFTimmy/rector-test

The core issue seems to be dealing with the intersection @var type of `Collection|Lesson[]`

## Expected Behaviour

No error.

**Comment by TomasVotruba** [comment]
What Rector version do you use? Intersection was fixed in recent week

**Comment by UFTimmy** [comment]
Howdy, thanks for replying so quickly.

Like I said in the ticket, I was using dev-master, but I "downgraded" to 0.6.12 and still receive the same error.

I linked to the intersection ticket, I am the one who opened that one too. The fix there made the original error go away, but made this exception pop up instead.

**Comment by TomasVotruba** [comment]
I just scanned the issue quickly, my bad.
I'll look at the repository you provided, thank you.
That helps a lot :+1:
