### ISSUE TITLE
[DX] Make sure "create" command is in 3rd party install

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#2734]
Now it's missing :/

**Comment by TomasVotruba** [comment]
Done

**Comment by alfredbez** [comment]
Still missing for me in version `0.6.13`:
```
abez@abez-XPS-13-9370:~/projects/github/oxideshop_ce$ grep rector composer.json 
        "rector/rector-prefixed": "^0.6.13"
abez@abez-XPS-13-9370:~/projects/github/oxideshop_ce$ vendor/bin/rector create
Rector v0.6.13


                                    
  Command "create" is not defined.  
```
![image](https://user-images.githubusercontent.com/1001186/73256602-7d4ed280-41c2-11ea-8a08-2baf458439a9.png)

Maybe I'm doing something wrong, not sure.

I also tried to use the docker container, failed with another message:
```
abez@abez-XPS-13-9370:~/projects/github/oxideshop_ce$ docker run -v $(pwd):/project rector/rector:latest create
Rector No version set (parsed as 1.0.0)@


In ConfigurationFactory.php line 60:
                                                          
  First, create config file "/rector/create-rector.yaml"  
                                                          

create-rector [-h|--help] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-c|--config CONFIG] [-s|--set SET] [--debug] [--xdebug] [-d|--working-dir WORKING-DIR] [--] <command>

abez@abez-XPS-13-9370:~/projects/github/oxideshop_ce$ docker run -v $(pwd):/project rector/rector:latest create --config /project/rector.yaml
Rector No version set (parsed as 1.0.0)@
Config file: ../project/rector.yaml


In ConfigurationFactory.php line 60:
                                                          
  First, create config file "/rector/create-rector.yaml"  
                                                          

create-rector [-h|--help] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-c|--config CONFIG] [-s|--set SET] [--debug] [--xdebug] [-d|--working-dir WORKING-DIR] [--] <command>
```
I've tried also using the tag `0.6.13` instead of `latest`:
```
abez@abez-XPS-13-9370:~/projects/github/oxideshop_ce$ docker run -v $(pwd):/project rector/rector:0.6.13 create
Rector No version set (parsed as 1.0.0)@


In RecipeGuard.php line 43:
                                                                               
  Make sure "package", "name", "node_types", "code_before", "code_after", "de  
  scription", "source", "set" keys are present in "parameters > rector_recipe  
  "                                                                            
                                                                               

create-rector
```
The keys are there:
```
abez@abez-XPS-13-9370:~/projects/github/oxideshop_ce$ grep ':' rector.yaml | awk -F':' '{print $1}'
parameters
    rector_recipe
        package
        name
        node_types
        description
        code_before
        code_after
        source
        set
abez@abez-XPS-13-9370:~/projects/github/oxideshop_ce$
```

**Comment by TomasVotruba** [comment]
Try dev-master, last release was 8 days ago and this issue was closed 7 days ago

**Comment by alfredbez** [comment]
:man_facepalming: works, thanks :+1:

**Comment by TomasVotruba** [comment]
I'll release new version this week to prevent it

**Comment by TomasVotruba** [comment]
New version is out:
https://github.com/rectorphp/rector/releases/tag/v0.6.14
