### ISSUE TITLE
Problems with rector and pestphp when installed together. 

### ISSUE THREAD

**Issue by tomasnorre** [rectorphp/rector#6433]
Hi @TomasVotruba and @nunomaduro,

Disclaimer: To be honest I don't know if this belongs into the rector/rector repository or the pestphp/pest repository. I'm just hoping that we can reach a solution on this topic.

I have a problem with a project when using both rector and pest. The problem has to do with load-order as I see it.

My requirements atm: 
```
pestphp/pest 1.2.1
rector/ 0.11.4
``` 

The Rector checks if function `expects` already exists in the global namespace, if not creating it [1]. Pest is creating in, in the global namespace [2].

This leads to this error when running my rector command: 

```shell 
PHP Fatal error:  Cannot redeclare expect() (previously declared in /home/runner/work/rector-pest-problem/rector-pest-problem/vendor/rector/rector/vendor/scoper-autoload.php:170) in /home/runner/work/rector-pest-problem/rector-pest-problem/vendor/pestphp/pest-plugin-expectations/src/Autoload.php on line 20
```

1) 
https://github.com/rectorphp/rector/blob/568d9ef7f59ba1105c17da7100e397ed1a4417c2/vendor/scoper-autoload.php#L168
```php 
if (!function_exists('expect')) {
    function expect() {
        return \RectorPrefix20210517\expect(...func_get_args());
    }
}
```

https://github.com/pestphp/pest-plugin-expectations/blob/master/src/Autoload.php#L20
2) 
```php 
function expect($value = null)
{
    if (func_num_args() === 0) {
        return new Extendable(Expectation::class);
    }

    return new Expectation($value);
}
```

I have created a small demo repository for this propose: 
https://github.com/tomasnorre/rector-pest-problem

Where you can also see the CI run: 
https://github.com/tomasnorre/rector-pest-problem/runs/2610735473?check_suite_focus=true#step:7:4

## How to reproduce: 

```shell
$ git clone https://github.com/tomasnorre/rector-pest-problem
$ cd rector-pest-problem
$ composer install 
$ ./vendor/bin/rector 
``` 
Best
Tomas

**Comment by sabbelasichon** [comment]
This seems to be a duplicate here #6432

**Comment by tomasnorre** [comment]
For sure looks like it.

**Comment by tomasnorre** [comment]
Strange that I didn't see that issue beforehand. Sorry for that.

**Comment by sabbelasichon** [comment]
No problem. Maybe we could close one of them.

**Comment by sabbelasichon** [comment]
@TomasVotruba I am on it. Reason found. Gonna try to fix it.

**Comment by sabbelasichon** [comment]
This is fixed by rector/rector-src#69

**Comment by tomasnorre** [comment]
Thanks for acting this fast.

If I see it correctly this is already part of the 0.11.5 release. 
Unfortunately the problem is still there.

**Comment by sabbelasichon** [comment]
No, i think it is still in the main branch only.

**Comment by tomasnorre** [comment]
My bad, read it wrong. The commit is made after the latest release. Thanks for taking care.

**Comment by olivernybroe** [comment]
@tomasnorre haha we must have created the issue at almost the same time 😆

**Comment by tomasnorre** [comment]
Yeah. Looks like it :)

**Comment by olivernybroe** [comment]
Just for reference, Pr's has been opened in Pest also to wrap all global functions in `function_exists` statements. 👍

**Comment by sabbelasichon** [comment]
Good catch. Thank you.

**Comment by TomasVotruba** [comment]
@olivernybroe Thanks :+1:  That's always the best practise, or even better namespace it like we do with classes to avoid same problem.

**Comment by olivernybroe** [comment]
@TomasVotruba do we have a rector rule to check and fix this automatically? 😆

**Comment by TomasVotruba** [comment]
@olivernybroe Glad you asked :D 
https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#renamefunctionrector

**Comment by olivernybroe** [comment]
@TomasVotruba Ah yeah 👍 We have the rename one, which is great for taking care of changing functions to namespaced functions, cool!

What about one that wraps global functions in `function_exists`? 😄

**Comment by TomasVotruba** [comment]
> What about one that wraps global functions in function_exists? :D 

That would actually overpower the other functions, that would fatal error. Imagine 2 packages with same-named function:

```php
// package A

if (! function_exists('me_first')) {
    function me_first(string $value)
    {
    }
}


// package B

if (! function_exists('me_first')) {
    function me_first(int $value)
    {
    }
}



// your code
me_first(10);


// code of package A
me_first('hey');
```

What will happen? Depends on OS, file name, package name and sorting algorithm of composer that will prefer one or the other. Most likely :boom:  :D 


<br>

This code smell actually shut down Rector ecosystem ~2 weeks ago. php-parser and PHP_CodeSniffer emulated `T_ENUM` tokens in 2 different ways:

```php
if (defined('T_ENUM') === false) {
    define('T_ENUM', 5005);
}


if (defined('T_ENUM') === false) {
    define('T_ENUM', 'php_cs_enum');
}
```

I had a full day of work to figure this out and patch it :)

**Comment by olivernybroe** [comment]
@TomasVotruba Oh wauw :O 

Yeah that kinda makes sense, but sounds really scary
