### ISSUE TITLE
[Parallel] Could not process some files, due to: "Child process error: ".

### ISSUE THREAD

**Issue by rajyan** [rectorphp/rector#7056]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 77a4582d5044446b8da43ab91a09082fa0413a23           |

Rector fails with
```
[ERROR] Could not process some files, due to:                                                                          
         "Child process error: ".
```
which has no information about the error.

Rector works fine with
```php
$parameters->set(Option::PARALLEL, false);
```
so it is something related to parallel.

some parts of these issues might be related,
https://github.com/rectorphp/rector/issues/6971
https://github.com/rectorphp/rector/issues/6912

## Minimal PHP Code Causing Issue

I'm trying to make a repo to reproduce the problem, but not succeeded yet.
It's hard because the process fails randomly (different places when using `--debug` option) and sometimes success if I change the
`PARALLEL_TIMEOUT_IN_SECONDS` or `PARALLEL_MAX_NUMBER_OF_PROCESSES` options.
I'll try narrowing the scope and create a repo in this weekend.

## Expected Behaviour

No errors. Also, a more helpful error message.

**Comment by rajyan** [comment]
@TomasVotruba 
I'll investigate it deeper in this weekend, so could you keep this issue open for a while?
I want some more information if someone is having a similar issue.

**Comment by rajyan** [comment]
Working on this now.

**Comment by rajyan** [comment]
I’ll reopen with reproducing repos when I have time

**Comment by rajyan** [comment]
@TomasVotruba 
This was fixed somewhere between 0.12.17 and 0.12.23! Thank you@

**Comment by Sergiobop** [comment]
I think this is not fixed, i'm having the same issue and i use 0.12.23

**Comment by gebi84** [comment]
I have same issue with 0.13.3

I tested with only 1 file, and get an empty Error with exitCode 255

with `$rectorConfig->disableParallel();` it works

I think this is an false error. Error also happens, if i set an empty rule set.

**Comment by TomasVotruba** [comment]
Thanks for reporting.
We'll need a minimal reproducer repository, to be able to figure out the root of the issue.

**Comment by gebi84** [comment]
> Thanks for reporting. We'll need a minimal reproducer repository, to be able to figure out the root of the issue.

composer.json
```json
{
    "name": "gebha/rector",
    "type": "project",
    "require": {
        "rector/rector": "^0.13.3"
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    }
}

```

src/Test.php
```php
<?php

declare(strict_types=1);

namespace App;

class Test
{
    protected string $foo;

    public function __construct(string $foo)
    {
        $this->foo = $foo;
    }
}
```

rector.php
```php
<?php

declare(strict_types=1);

use Rector\CodeQuality\Rector\Class_\InlineConstructorDefaultToPropertyRector;
use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\LevelSetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__ . '/src'
    ]);
};
```

`vendor/bin/rector process --debug --clear-cache --no-diffs -vvv`

 [ERROR] Could not process some files, due to:
         "Child process error: ".

**Comment by TomasVotruba** [comment]
This will probably work on my machine as Rector CI runs on similar config. That's why we need repository to have exact reproducer.

**Comment by gebi84** [comment]
I cant't give you more than that. It runs under windows, with an AMD 5950x on laragon with php 7.4.26

**Comment by TomasVotruba** [comment]
Windows might be the issue.

**Comment by UtopieStudio** [comment]
I just encountered this issue as well.
Windows 10 / PHP 7.4.26

```php
use Rector\Php74\Rector\Property\TypedPropertyRector;
use Rector\Set\ValueObject\SetList;
use Rector\Config\RectorConfig;

return static function (RectorConfig $rectorConfig): void {
    // here we can define, what sets of rules will be applied
    // tip: use "SetList" class to autocomplete sets
    $rectorConfig->sets([
        SetList::CODE_QUALITY
    ]);
    
    // register single rule
    $rectorConfig->rule(TypedPropertyRector::class);
    //$rectorConfig->disableParallel();
};
```

> $ vendor/bin/rector process Connections --dry-run
 2/2 [============================] 100%

>[ERROR] Could not process some files, due to:
"Child process error: ".

Enabling:
```php
$rectorConfig->disableParallel();
```
Give the OK Rector is done, message, no files are changed.

**Comment by samsonasik** [comment]
`no files are changed` may means everything ok, we need a failing test case for it.

I don't have windows10 at my local dev, so can't test the exact environment.

We need the exact step by step to reproduce the issue, (the file, the config, the command that run), better to use Github repository with github action running.

You may can create reproducible repository with Github action with windows for it https://github.blog/changelog/2022-01-11-github-actions-jobs-running-on-windows-latest-are-now-running-on-windows-server-2022/
