### ISSUE TITLE
 The file "vendor/symplify/better-phpdoc-parser/src/config/config.yml" does not exist.

### ISSUE THREAD

**Issue by vasilvestre** [rectorphp/rector#732]
Running this command : 

`~/.composer/vendor/bin/rector process ./src/ --autoload-file ./vendor/autoload.php`

I have this output : 
```bash
The file "/home/vsilvestre/Projets/relaischateaux/vendor/symplify/better-phpdoc-parser/src/config/config.yml" does not exist in /home/vsilvestre/  
  Projets/relaischateaux/vendor/symplify/better-phpdoc-parser/src/config/config.yml (which is being imported from "/home/vsilvestre/.composer/vendo  
  r/rector/rector/packages/NodeTypeResolver/src/config/config.yml").
```

(I feel like I already asked help for something like this but can't find the issue)

**Comment by TomasVotruba** [comment]
I think was one of issues in past version.

Do you use last tagged one?

**Comment by carusogabriel** [comment]
@TomasVotruba I get this issue if I try to install Rector globally or run from my fork as well.

**Comment by TomasVotruba** [comment]
I'm on it :+1:

**Comment by TomasVotruba** [comment]
### Steps to reproduce

```bash
composer global require rector/rector
# using version 0.3.15
```

- **OK**

```bash
# in /var/www
~/.composer/vendor/bin/rector
```

- **OK**

```bash
# in /var/www/friendsofphp.org project
 ~/.composer/vendor/bin/rector
```

- **ERROR:** due to missing config file

```                                                                                                                                        
  Cannot autowire service "Rector\NodeTypeResolver\PhpDoc\NodeAnalyzer\PhpDocInfoFqnTypeDecorator": argument "$nodeTraverser" of method  
   "__construct()" references class "Symplify\BetterPhpDocParser\Ast\NodeTraverser" but no such service exists.                          
                                                                                                           
```

**Comment by TomasVotruba** [comment]
The implementatoin of `VendorDirProvider` was incorrectly using the project's vendor to load Rectors deps.

This works for me, but it might not for you. 

Could you test it please?

```
subl ~/.composer/vendor/symplify/package-builder/src/Composer/VendorDirProvider.php
```

↓


```php
<?php declare(strict_types=1);

namespace Symplify\PackageBuilder\Composer;

use Composer\Autoload\ClassLoader;
use Nette\Utils\Strings;
use ReflectionClass;

final class VendorDirProvider
{
    public static function provide(): string
    {
        $path = __DIR__;
        while (! Strings::endsWith($path, 'vendor') && $path !== '/') {
            $path = dirname($path);
        }

        if ($path !== '/') {
            return $path;
        }

        return self::reflectionFallback();
    }

    private static function reflectionFallback(): string
    {
        $classLoaderReflection = new ReflectionClass(ClassLoader::class);

        return dirname(dirname($classLoaderReflection->getFileName()));
    }
}
```

**Comment by vasilvestre** [comment]
This is fixed or you would like me to try it ?

**Comment by vasilvestre** [comment]
``````

**Comment by TomasVotruba** [comment]
There might be conflict with origin dependencies.

Try removing it first:

```
comoser global remove rector/rector
```

If error remains, investigate globally installed dependencies:

```
composer global show
```

**Comment by TomasVotruba** [comment]
Closing as reported issues was resolved.

For prefixed rector, report on the repo: https://github.com/rectorphp/rector-prefixed

**Comment by carusogabriel** [comment]
Reopening this as I can't get this working using my local fork.

```
$ ../rector/bin/rector process src/ --level code-quality
```

gives me
```

In FileLoader.php line 168:
                                                                                                                                                                                                                  
  The file "/home/carusogabriel/Code/PhpSpreadsheet/vendor/symplify/better-phpdoc-parser/src/config/config.yml" does not exist in /home/carusogabriel/Code/PhpSpreadsheet/vendor/symplify/better-phpdoc-parser/s  
  rc/config/config.yml (which is being imported from "/home/carusogabriel/Code/rector/packages/NodeTypeResolver/src/config/config.yml").                                                                          
                                                                                                                                                                                                                  

In FileLocator.php line 44:
                                                                                                                                 
  The file "/home/carusogabriel/Code/PhpSpreadsheet/vendor/symplify/better-phpdoc-parser/src/config/config.yml" does not exist.  
                                                                                                                                 
```

**Comment by TomasVotruba** [comment]
Version?

**Comment by carusogabriel** [comment]
@TomasVotruba Master, last commit, I just did a `git pull --rebase -p` in the `master` branch

**Comment by TomasVotruba** [comment]
Since v0.3.18 it should.

**Comment by TomasVotruba** [comment]
I've just released v0.3.19 with other fixes, including this.

**Comment by vasilvestre** [comment]
Could you upgrade rector prefixed so ?

**Comment by carusogabriel** [comment]
@vasilvestre This is an issue: `rector-prefixed` never updates.

@TomasVotruba What can we do about it?

**Comment by TomasVotruba** [comment]
It needs to be fixed here: https://github.com/rectorphp/prefixer

I don't have time now, I focus fully on Rector development. Any help is welcomed

**Comment by carusogabriel** [comment]
> I don't have time now, I focus fully on Rector development. Any help is welcomed

@TomasVotruba I disagree. If we made `rector-prefixed` to solve our conflicts problems, we should keep it up to date. I **always** get people complaining about it, **always**.

**Comment by TomasVotruba** [comment]
What do you disagree with?
