### ISSUE TITLE
Cannot process files

### ISSUE THREAD

**Issue by sh1hab** [rectorphp/rector#8005]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.17.1          |

Tried to run the `./vendor/bin/rector process ` and got **fatal errors file /media/mac/New does not exist. Could not process some files, due to:                                                                          
         "Child process error: ".** 

I am using Ubuntu 22

**Comment by samsonasik** [comment]
do you have path with space?

**Comment by larryn** [comment]
I have the same problem and I do have a path with spaces. If I remove the space from the path then things proceed as expected.

% pwd
/Volumes/Projects/Silicon Travel/TripSiGuest
% ./vendor/bin/rector process --dry-run -vvv ./lib/CommonBundle/src/Entity/ContentAds/AdListing.php
{"fatal_errors":["The file \"/Volumes/Projects/Silcon\" does not exist."]}
                                                                                                                        
 [ERROR] Could not process some files, due to:                                                                          
         "Child process error: ".

**Comment by TomasVotruba** [comment]
Fixed in https://github.com/rectorphp/rector-src/pull/4553

**Comment by Konafets** [comment]
@TomasVotruba I still having this issue with latest version and even on `dev-main`. Error is gone when removing the space in path.

**Comment by samsonasik** [comment]
@Konafets we need e2e test for windows use case mentioned at https://github.com/rectorphp/rector-src/pull/4553#issuecomment-1644950080

**Comment by Konafets** [comment]
For the record: I am on a Mac with PHP 8.2

**Comment by samsonasik** [comment]
@Konafets could you create a reproducible repo for that? Thank you.

**Comment by samsonasik** [comment]
Ok, I can reproduce on mac:

```
➜  target vendor/bin/rector 
 0/1 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%{"fatal_errors":["Cannot load resource \"/Users/samsonasik/www/spaced\"."]}
                                                                                                                        
 [ERROR] Could not process some files, due to:                                                                          
         "Child process error: ".                                                                                       
                                         
```

I will push a reproducible repo.

**Comment by samsonasik** [comment]
oh, github only allow non-spaced name:

![Screen Shot 2023-07-31 at 08 51 05](https://github.com/rectorphp/rector/assets/459648/3523821e-4641-4d80-9d32-894bacebf4a6)

I will update the sample use case here:


[spaced prj sample.zip](https://github.com/rectorphp/rector/files/12210766/spaced.prj.sample.zip)

To reproduce:

- extract the zip file
- go:

```bash
cd spaced\ prj\ sample/
cd target

➜  target git:(main) vendor/bin/rector      
 0/1 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%{"fatal_errors":["Cannot load resource \"/Users/samsonasik/www/spaced\"."]}
                                                                                                                        
 [ERROR] Could not process some files, due to:                                                                          
         "Child process error: ".                                                                                       
                                         
```

**Comment by samsonasik** [comment]
The issue is only happen on parallel process, that means the path definition for new WorkerRunner is exclude the spaced paths.
