### ISSUE TITLE
Incorrect behavior of ImproveDoctrineCollectionDocTypeInEntityRector

### ISSUE THREAD

**Issue by AlexeyKosov** [rectorphp/rector#8788]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/dacf76a6-5472-4e02-9bfd-c2391417f741 - with annotation
https://getrector.com/demo/765a68b0-bbbc-41b5-bd10-0e0abf569505 - with attribute

```php
<?php
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity()]
class SomeClass
{
    /**
     * @var Collection|Trainer[]
     */
    #[ORM\OneToMany(targetEntity: Trainer::class, mappedBy: "trainer")]
    private $trainings = [];
    
    public function getTrainings()
    {
        return $this->trainings;
    }
    
    public function setTrainings($trainings)
    {
        $this->trainings = $trainings;
    }
}
```

### Responsible rules

* `ImproveDoctrineCollectionDocTypeInEntityRector`

## Expected Behavior

The rule works only with annotations and does not work with attributes.

**Comment by TomasVotruba** [comment]
Thanks for reporting :+1:  I'm looking into this

**Comment by AlexeyKosov** [comment]
@TomasVotruba 
Thanks for looking into it. While you're on it, just wanted to mention that it would be great if this rule also supported improving the getter (currently, it works only with the property and its setter)

And I just noticed one more issue with it - the rule will always use `int` as the collection key (it's hardcoded). But in some cases, collections use a `string` key, e.g. in `ORM\OneToMany` with `indexBy`. Do you think it's worth submitting a new case?

**Comment by TomasVotruba** [comment]
> And I just noticed one more issue with it - the rule will always use int as the collection key (it's hardcoded). But in some cases, collections use a string key, e.g. in ORM\OneToMany with indexBy. Do you think it's worth submitting a new case?

I think it makes sense. I'm not familiar with Doctrine collections in such deep level. Could you covert this case?

**Comment by TomasVotruba** [comment]
> it would be great if this rule also supported improving the getter (currently, it works only with the property and its setter)

Done :heavy_check_mark:

**Comment by TomasVotruba** [comment]
As for the getter, check: `AddReturnDocBlockToCollectionPropertyGetterByToManyAnnotationRector`

The best practise is to use full `\Rector\Doctrine\Set\DoctrineSetList::TYPED_COLLECTIONS` set at once :+1:

**Comment by AlexeyKosov** [comment]
@TomasVotruba 
Does the demo with attributes work for you? https://getrector.com/demo/765a68b0-bbbc-41b5-bd10-0e0abf569505
Looks like it still does not support attributes.

**Comment by TomasVotruba** [comment]
@AlexeyKosov Ths fix is here https://github.com/rectorphp/rector-doctrine/pull/339

Demo is not always loading external packages like Doctrine, so attributes might not be available.
What results do you get locally?

**Comment by AlexeyKosov** [comment]
Yep, locally it turns out to work properly. Thanks!
