### ISSUE TITLE
Short closure to callable syntax breaks when argument count differs

### ISSUE THREAD

**Issue by imliam** [rectorphp/rector#9456]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 2.2.4             |

Rector is aggressively converting short closures to first-class callable syntax, even when it doesn't make sense.

## Minimal PHP Code Causing Issue

For example, take this case:

```diff
- return array_all($input, fn ($item): bool => is_scalar($item));
+ return array_all($input, is_scalar(...));
```

Here, `array_all` will invoke a callback with `$value, $key` parameters, but `is_scalar` is only expecting one parameter. This causes an error to occur:

> is_scalar() expects exactly 1 argument, 2 given

(I can't get it working on the demo, but I believe [this](https://getrector.com/demo/b89102d9-b6ad-4236-8b3a-fefe396427d6) should do it? Maybe I got the wrong rule, though.)

## Expected Behaviour

The Rector rule should only convert to first-class callables when the number of arguments being passed to the callable matches the number it expects to receive.

**Comment by samsonasik** [comment]
This should be resolved in dev-main already :)

Please try : 

```
composer config minimum-stability dev
composer config prefer-stable true
composer update rector/rector:dev-main
```

**Comment by TomasVotruba** [comment]
Rector **2.2.5** including this fix is out now: https://github.com/rectorphp/rector/releases/tag/2.2.5

If problem still persist, we'll need framework-agnostic failing example from http://getrector.com/demo
Only that way we can see root cause and fix it 👍
